/**
 * USER_NOT_FOUND
*/
export const USER_NOT_FOUND = `USER NOT FOUND`;

/** 
 * USER_REGISTERD
*/
export const USER_REGISTERD = `USER REGISTERD SUCCESSFULLY WITH id:`;

/**
 * USER_NOT_REGISTER
*/
export const USER_NOT_REGISTER = `UNABLE TO REGISTER USER TRY AGAIN LATER`;

/**
 * USER_ALREADY_EXIST 
*/
export const USER_ALREADY_EXIST = `USER ALREADY EXIST`;

/**
 * USER_AUTHENTICATED
*/
export const USER_AUTHENTICATED = `USER AUTHENTICATED SUCCESFULLY`;

/**
 * INVALID_CREDENTIALS
*/
export const INVALID_CREDENTIALS = `INVALID CREDENTIALS`;

/**
LOG_IN_SUCCESS
*/
export const LOG_IN_SUCCESS = `USER LOG IN SUCCESSFUL`;

